name = "data-parser-1a-lv"
main = "src/index.ts"
compatibility_date = "2023-10-23"
usage_model = "bundled"

kv_namespaces = [
  { binding = "STORAGE", id = "630027a2605546b89cd0be9b51c53902", preview_id = "630027a2605546b89cd0be9b51c53902" }
]
